import Link from "next/link";
import { BenchmarksTable } from "@/components/methods/BenchmarksTable";

/**
 * Renders the exact same `BenchmarksTable` used on `/methods` -- not a
 * re-typed copy of its numbers. A landing page that hand-copies benchmark
 * figures is exactly how a page ends up quoting a stale or fabricated
 * number after the source JSON changes; importing the component means
 * this section and Methods can never disagree. No score above 0.66 is
 * shown anywhere on this page, and the hybrid VQC's underperformance is
 * stated, not hidden in a footnote.
 */
export function EvidenceSection() {
  return (
    <section id="evidence" className="scroll-mt-16 border-t border-surface-3">
      <div className="mx-auto max-w-6xl px-4 py-14 sm:px-6 sm:py-20">
        <p className="font-mono text-xs font-semibold uppercase tracking-[0.2em] text-accent">Repository Evaluation</p>
        <h2 className="mt-3 text-2xl font-bold tracking-tight text-ink-primary sm:text-3xl">
          What the evaluation actually shows
        </h2>
        <p className="mt-3 max-w-2xl text-sm leading-relaxed text-ink-muted">
          Every number below is read directly from{" "}
          <code className="text-ink-primary">qknee/artifacts/kaggle_benchmark_summary.json</code>, generated by{" "}
          <code className="text-ink-primary">qknee/models/evaluate.py</code>. Nothing here is a marketing figure —
          it&apos;s the same evaluation reproduced on <Link href="/methods" className="text-accent hover:underline">
            the Methods page
          </Link>
          .
        </p>

        <div className="mt-8">
          <BenchmarksTable />
        </div>
      </div>
    </section>
  );
}
